baseURL = "http://rtarun9.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

enableEmoji = true

title = "Tarun Ramaswamy"

theme = "PaperMod"

# Automatically generate robots.txt
enableRobotsTXT = false


[params.profileMode]
enabled = true
title = "Tarun Ramaswamy"

subtitle = "Computer Science Student | Graphics Programmer"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tarun-ramaswamy-931426200/"

  [[params.socialIcons]]
  name = "Github"
  url = "https://github.com/rtarun9"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/rtarun0"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCXASE11l2Y94oFE86oX-T8w"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"
    weight = 2
    url = "/posts/projects/"
    # Display name
    name = "Projects"

    # Weights are used to determine the ordering
    
    [[menu.main]]
    # Unique identifier for a menu item
    identifier = "about"
    url = "/posts/about/"
    weight = 1
    # Display name
    name = "About"


  [[menu.main]]
    identifier = "github"
    url = "https://github.com/rtarun9"
    weight = 5
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'> Github</span>"
